### PR TITLE
fix: Added Open VSX build (#914)

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Will the bundled version also require `keytar`?

**Comment by JohnstonCode** [comment]
@edgardmessias think that should get it all working. Can you see any issues?

**Comment by edgardmessias** [comment]
I solved last issue.

When we use webpack, not necessary use production dependency, because the webpack bundle it into main package.
The `vsce` command only keep production dependency in node_modules.

So, when we use `yarn add iconv-lite jschardet`, it will generate only direct dependencies, avoiding a lot of others.

**Comment by JohnstonCode** [comment]
What does that increase the VSCode vsix by?

**Comment by JohnstonCode** [comment]
You have added them a deps in the package.json

**Comment by edgardmessias** [comment]
Oh, sorry

**Comment by edgardmessias** [comment]
About node_modules, look:
Before:
https://github.com/JohnstonCode/svn-scm/actions/runs/200282735
image

After:
https://github.com/JohnstonCode/svn-scm/actions/runs/200729344
image

**Comment by JohnstonCode** [comment]
Ah yes much better! Nice work.

**Pull request merged**
