### PR TITLE
fix: clean up temp svn files when closed

### PR DESCRIPTION
**Pull request by JohnstonCode**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
@Yanpas

**Comment by edgardmessias** [comment]
For cache, Look: https://github.com/JohnstonCode/svn-scm/blob/master/src/svnContentProvider.ts#L136

**Comment by JohnstonCode** [comment]
After looking at this further not sure what could be cached as the content and Uri are passed to the temp Svn class. The calls to Svn have already been made.

**Pull request merged**
