### PR TITLE
fix: diff files now have unique paths

### LINKED ISSUE #658: Wrong revision diff file with files with the same name
- VSCode Version: 1.37.1
- OS Version: Windows 10
- Extension Version: 1.54.4

## Issue ##
When looking at the diffs in the "Repositores" block, in the SVN tab, files with the same name use the same diff file in the temporary directory. This can happen quite often in multi module Maven projects, which have the file pom.xml in different subfolders.

I was wondering if it would fix it if the whole path of the file was used instead of the basename.
https://github.com/JohnstonCode/svn-scm/blob/b26602f2237938106ebaaba52bf7dc54aecf00cc/src/tempFiles.ts#L16

## Screenshots ##
image

Those 2 pom.xml are in different directories in the source code, but the diff viewer makes both link to the same diff file.
image

### PR DESCRIPTION
**Pull request by JohnstonCode**
fixes #658

### CODE REVIEW

**Comment by edgardmessias** [comment]
Why no use the `tmp` library? https://www.npmjs.com/package/tmp

**Comment by JohnstonCode** [comment]
I dont think using it gives any advantage, the code is concise already. The only benefit of the `tmp` library is the clenup. But in this situation it is extra effort to check when the file is no longer in use.

**Comment by JohnstonCode** [comment]
While im at it i will rename the function to somethnig more useful and add some tests. Maybe `createTempSvnRevisionFile`

**Pull request merged**
