### PR TITLE
Fix rev cmds

### PR DESCRIPTION
**Pull request by Yanpas**
Reopen of #490

### CODE REVIEW

**Comment by JohnstonCode** [comment]
`svn: E125002: URL 'file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/svn_server_4051CK5bSvqlDp7V/../../../../../../var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/svn_checkout_405165ys5lp2PFj4/new.txt' contains a '..' element`

Still broken on mac

**Comment by Yanpas** [comment]
Azure doesn't show what has happened. Manually launched build pipeline for my repository, the logs lack any info except console.error (`Constructor called in sync fashion`). Maybe something wrong woth mocha?

[log_73_2.zip](https://github.com/JohnstonCode/svn-scm/files/2987669/log_73_2.zip)

**Comment by JohnstonCode** [comment]
My last comment is what is wrong. Look at the mac os debug commits if you want azure to show you the errors

**Comment by JohnstonCode** [comment]
Not sure why it doesnt show what tests are failing

**Comment by JohnstonCode** [comment]
@edgardmessias can you get the tests to be outpuuted again?

**Comment by Yanpas** [comment]
Now I can see azure details.

If you open codeinsides version there will be detailed information (https://github.com/Microsoft/vscode/pull/67640).

```
rejected promise not handled within 1 second: Error: spawn /usr/local/bin/svn ENOENT

stack trace: Error: spawn /usr/local/bin/svn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

That's strange

**Comment by edgardmessias** [comment]
I will check tomorrow

Em qua, 20 de mar de 2019 6:56 PM, Yan Pashkovsky <notifications@github.com>
escreveu:

**Comment by edgardmessias** [comment]
@Yanpas, the issue is caused by `svn switch` command

The line below is called after repository are closed or disposed
https://github.com/JohnstonCode/svn-scm/blob/8471670e67a0ca6d12f7c8ebd050f48eddb017a2/src/repository.ts#L380

**Comment by Yanpas** [comment]
Problem is that on macos `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/svn_checkout_943wHkp8MSKLPql`
relative to `/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/svn_checkout_943wHkp8MSKLPql/new.txt`

results in `../../../../../../../var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/svn_checkout_943wHkp8MSKLPql/new.txt`

**Comment by Yanpas** [comment]
Fixed tests, but we need to do something with macos, maybe run readlink. Don't have experience with this OS. https://dev.azure.com/johnstoncode/Svn-scm/_build/results?buildId=157

**Comment by JohnstonCode** [comment]
Testing now. I have found a use case for me.

**Comment by JohnstonCode** [comment]
@Yanpas doesnt work for me. I can see the repository but if i click on it i don't get its history. Same for file history. Not getting any errors either

**Comment by Yanpas** [comment]
Maybe we are running svn servers of different versions... svn log now appends `@` to the end of the file each time.

Do logged commands output something meaningful?

**Comment by Yanpas** [comment]
There are some other issues, will open PR when will be ready

**Pull request closed without merging**
