### PR TITLE
Added support to SVN status in file explorer (Close #34)

### LINKED ISSUE #34: Feature: SVN status in file explorer
I'd love to see the SVN status indicated with colors/icons in the file explorer similar to the GIT integration in 1.18:

GIT file explorer decorations
Image stolen from https://github.com/Microsoft/vscode/issues/178

Maybe it's possible to reuse the git code from the official extension: https://github.com/Microsoft/vscode/tree/master/extensions/git ? 

I'd be happy to help out, if you can provide me some pointers on where to start (I'm new to VSCode)

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by edgardmessias** [comment]
Maybe, I need fix conflict with #137

**Comment by JohnstonCode** [comment]
@edgardmessias you fixed the conflict?

**Comment by edgardmessias** [comment]
No, first, merge the #137, after this, I fix

**Comment by JohnstonCode** [comment]
merged

**Comment by JohnstonCode** [comment]
also can we not just use the "enableProposedApi": true?

**Comment by edgardmessias** [comment]
If you set `"enableProposedApi": true`, you not can publish to marketplace

**Comment by edgardmessias** [comment]
@JohnstonCode, Conflict fixed.

**Pull request merged**
