### PR TITLE
update remote changes as well on refresh button click

### PR DESCRIPTION
**Pull request by Yanpas**

### CODE REVIEW

**Comment by Yanpas** [comment]
You mean there should be no network activity on refresh button?

**Comment by edgardmessias** [comment]
Create a option in configuration

**Comment by edgardmessias** [comment]
Changes in default actions need caution

**Comment by Yanpas** [comment]
I understand your point and will commit these changes. I still don't like this solution since this setting is hidden and not obvious. We may ask what does user want in a pop-up and memorize his choice. Or introduce separate button at the status bar.

**Comment by JohnstonCode** [comment]
I agree with @edgardmessias i dont think we should mess with the functionality of the refresh button. I feel like the expected behaviour of that button is to refresh the currect selected repository in the SCM view.

Maybe this could be done with a config option on the status bar refresh button?

**Comment by Yanpas** [comment]
My proposal seemed more logical to me since update button is on top of both remote and local changes lists.
Status bar may have refresh button always visible and fetch button when remote changes are available

**Comment by Yanpas** [comment]
I propose the following:
image

If there are no updates then there is only one button which updates remote changes list. If there are then there is little button on the left which fetches all updates

**Comment by Yanpas** [comment]
PS I work with repository where some changes appear every 3-4 minutes and began to feel that I need this button :)

**Comment by JohnstonCode** [comment]
If that is the case couldn't you just change the `svn.remoteChanges.checkFrequency` time?

**Comment by Yanpas** [comment]
I don't want it to be five seconds, I just want to see what will change right before I will commit

**Comment by JohnstonCode** [comment]
Okay i see. Would a command `update all` be enough or do you want it assigned to a button?

**Comment by Yanpas** [comment]
Yes, I would like to have a button. Another possible approach, but not sure if it is available in API
image

**Comment by JohnstonCode** [comment]
Yeah you can add buttons to the title of resource groups

**Comment by Yanpas** [comment]
That seems to be impossible and currently available only for git. Didn't found any way to change anything except title for SourceControlResourceGroup

**Comment by JohnstonCode** [comment]
I can add the refresh button if you would like, Buttons need adding to the package.json

**Comment by JohnstonCode** [comment]
#366

**Pull request closed without merging**
