### PR TITLE
feat: New svn icon

### PR DESCRIPTION
**Pull request by Yanpas**
image

### CODE REVIEW

**Comment by JohnstonCode** [comment]
The svg looks good. What does the script have over the current way of creating repositories?

**Comment by Yanpas** [comment]
This script helped me to debug history view. I was tired to create some test repos on each machine. I thought it will be useful for other developers.

**Comment by JohnstonCode** [comment]
Can you create a `bin` dir in the root and put it in there please

**Comment by Yanpas** [comment]
done

**Pull request merged**
