### PR TITLE
Changed icons for BASE and HEAD, and hide for not SVN (Close #136)

### LINKED ISSUE #136: Changes icons alway on
Extension Version: 1.13.2

There are two icons appeared recently: changed with Head and changes with Base. There are two problems with them: they both have same icon, the same with git too. And they appear for files which do not belong to any svn working copy

### PR DESCRIPTION
**Pull request by edgardmessias**
Added green letter "H" for HEAD and blue letter "B" for base.
Hide the icons on non SVN repositories;

### CODE REVIEW

**Comment by johnjacobkenny** [comment]
The new icons do help, but the letters aren't that legible, is there some way to make the letters appear bigger? 
image

**Comment by edgardmessias** [comment]
You can edit SVGs

**Comment by JohnstonCode** [comment]
@johnjacobkenny Edit the SVSs  and see if you can create something clearer

**Comment by johnjacobkenny** [comment]
Is there any precedence I should keep in mind for the design of the button?
Also, I haven't worked with SVGs before, do you use any software to edit them? Something like Inkscape?

**Comment by JohnstonCode** [comment]
Not sure I try not to deal with graphics. 

I'm sure a quick google should throw something up.

As long as the design gits in the VS code I'm not fussy.

**Comment by edgardmessias** [comment]
SVN is like HTML, you can start here: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial

Or use Inkscape

**Pull request merged**
