### PR TITLE
Added support to configure the path to the svn executable

### PR DESCRIPTION
**Pull request by edgardmessias**
Like a GIT options.

### CODE REVIEW

**Comment by edgardmessias** [comment]
I need make more tests

**Comment by JohnstonCode** [comment]
Thanks alot for doing this. 

Nice work. I'll merge

**Comment by edgardmessias** [comment]
It is not good

Em 27 de nov de 2017 7:22 PM, "Christopher" <notifications@github.com>
escreveu:

**Comment by edgardmessias** [comment]
I'll make some corrections and send another pull request

**Pull request merged**
