### PR TITLE
Added revert package.json step

### LINKED ISSUE #706: Automatic release is broken
It seems to be removing the activation event from the package.json

### PR DESCRIPTION
**Pull request by JohnstonCode**
fixes #706

### CODE REVIEW

**Comment by edgardmessias** [comment]
@JohnstonCode , I am favor of `git checkout package.json`

A good action to add: https://github.com/actions/upload-artifact

We can run `vsce package -o svn-scm.vsix` and upload-artifact

**Comment by JohnstonCode** [comment]
@edgardmessias changed it to use git checkout. Would you want a vsix generating for every build?

**Comment by edgardmessias** [comment]
My idea is to generate only for pull requests, is more easy to users to download and test the solution.

**Comment by JohnstonCode** [comment]
Yeah create an issue that should be easy to add.

**Pull request merged**
