### PR TITLE
Try out new settings table layout

### PR DESCRIPTION
**Pull request by johnjacobkenny**
Trying out a different layout to organize settings. I'll update the configs that are missing afterwards.

### CODE REVIEW

**Comment by edgardmessias** [comment]
Nice

**Comment by edgardmessias** [comment]
@johnjacobkenny, maybe we can create a `tools` folder and create a script to read the `package.json` and generate the `table` section

**Comment by johnjacobkenny** [comment]
That makes sense. All the options mentioned under the `configuration.properties` object is what we need right?

**Comment by edgardmessias** [comment]
Yes

**Comment by johnjacobkenny** [comment]
I shall give it a try. TypeScript or just plain JS?

**Comment by edgardmessias** [comment]
TypeScript and add npm command to build tools

**Pull request merged**
