### PR TITLE
fix: Disable branch switching without common ancestor #372

### LINKED ISSUE #372: Disable branch switching without common ancestor
- VSCode Version:
- OS Version:
- Extension Version:1.40
- System Language:
- SVN Version: 1.9

## Issue ##
I work with big svn repo with following structure

- trunk
- branches
  - issues
    - Yanpas
      - issue123
  - features

I've accidenately switched to braches/issues (i thought that it will result in opening branches dir) which is pretty big and doesn't fit to my hdd. There were no warnings etc. I've found following line in src/svnRepository.ts:368:
```typescript
await this.exec(["switch", branchUrl, "--ignore-ancestry"]);
```

handle this exception in error or user's confiramtion.

### PR DESCRIPTION
**Pull request by Yanpas**
Fixes #372

### CODE REVIEW

**Comment by edgardmessias** [comment]
@Yanpas, create a new argument in `switchBranch` and move the prompt to commands

**Comment by edgardmessias** [comment]
We need prevent prompts in `svnRepository.ts` and `repository.ts`

**Comment by Yanpas** [comment]
Done

**Pull request merged**
