### PR TITLE
feat: Allow multi-line commit messages (close #471)

### LINKED ISSUE #471: Allow multi-line commit messages
When entering commit messages, both at the top of the SVN pane and in the top bar in the middle of the Visual Studio Code window, you can only enter a single line commit message. It gives the appearance of allowing you to enter multiple lines if you hold Shift + Enter to add new lines, but the final message to SVN comes through as a single line.

For anyone working on multiple items that they commit at once, such as multiple issues in a single file that are not necessarily related, entering multiple lines for your commit can be important.

It would be preferable that pressing "Enter" from the commit message box adds new lines to the commit dialog box and they do not get stripped when committing to your repo.

I know that it is not a limitation of SVN, as TortoiseSVN allows this.

### PR DESCRIPTION
**Pull request by edgardmessias**
Note: run before: `npm install && npm run build`

A solution to allow multi-line commit message, with webview

### CODE REVIEW

**Comment by edgardmessias** [comment]
Some print, the colors respect the theme:
image
image
image

**Comment by JohnstonCode** [comment]
If i write a commit message and click cancel i get this empty .git created

image

**Comment by edgardmessias** [comment]
O will check

**Comment by edgardmessias** [comment]
@JohnstonCode, I can't reproduce the bug with ".git" folder

**Comment by JohnstonCode** [comment]
I will re-test tonight

**Comment by JohnstonCode** [comment]
Seems my vs is bugged

**Pull request merged**
