### PR TITLE
chore: Fixed matrix build in .travis.yml

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Is there not a way we cant specify a range? Seems to be a pain having to change this everytime a new version is released.

**Comment by JohnstonCode** [comment]
Or would the better question be should we just support the latest version?

**Comment by edgardmessias** [comment]
Maybe a single build with loop.

To get a list of available version of vscode: https://vscode-update.azurewebsites.net/api/releases/stable

for each version, remove the .vscode-test folder, set the env CODE_VERSION and run test again

**Comment by JohnstonCode** [comment]
I think we should just test latest version + insiders

**Comment by JohnstonCode** [comment]
Yeah that works, then we only need to update when we up the engines version

**Comment by edgardmessias** [comment]
Updated for Travis, update for AppVeyor?

**Pull request merged**
