### PR TITLE
Hist lens

### PR DESCRIPTION
**Pull request by Yanpas**
Boom :)

### CODE REVIEW

**Comment by JohnstonCode** [comment]
I will fully review this tomorrow as I am free all day.

**Comment by Yanpas** [comment]
CHANGELOG.md was prettified by some git hook, very annoying. With --no-verify no it's identaical.

**Comment by JohnstonCode** [comment]
Can you remove all the `getCommitIcon` and just use a generic icon for a person or no icon at all?

**Comment by Yanpas** [comment]
> Can you remove all the `getCommitIcon` and just use a generic icon for a person or no icon at all?

Gravatar icons help track author visually, they exist in gitlens for the same reason. So I don't think it's a good idea.

Mine avatar is red robot e.g.:
image

**Comment by JohnstonCode** [comment]
Disregard that, Can we just have it default to false `svn.gravatars.enabled`

**Comment by JohnstonCode** [comment]
Actually thinking about it, some differentiation is good.

**Comment by Yanpas** [comment]
It doesn't expose any data since hash is transmitted. I think users won't just find this option in settings and will use default. If there is no network there will be no icons and network overhead is low. (I think chrome caches equal urls)

Concerning screenshot - line without avatar is BASE, just marker of current revision.

**Comment by JohnstonCode** [comment]
This Item history bit. Is there a way it can display the item it's showing the history for?

**Comment by JohnstonCode** [comment]
I mean in the item log where is no way to easily identify what the item log is for.

**Comment by Yanpas** [comment]
We may rename it to file history and/or add root item with it's name like in gitlens:
image

**Comment by JohnstonCode** [comment]
Yes!

**Comment by Yanpas** [comment]
done
image

**Comment by JohnstonCode** [comment]
the root item has the `copy message to clipboard` context menu on it

**Comment by JohnstonCode** [comment]
Yeah all looks good now.

**Comment by Yanpas** [comment]
woohoo :smile:

**Comment by Nukium** [comment]
Awesome !!!!

**Pull request merged**
