### PR TITLE
Added support to configure non-standard layout (Close #54)

### LINKED ISSUE #54: Feature: Support for non standard layouts
Create option in settings to allow users to define which layout is used.

Example:
```json
{
  "svn.layout.trunk": "trunk",
  "svn.layout.branches": "branches",
  "svn.layout.tags": "tags"
}
```

Non Standard:
```json
{
  "svn.layout.trunk": "main",
  "svn.layout.branches": "versions",
  "svn.layout.tags": "stamps"
}
```

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Would it be possible to update the changelog with your changes?

**Comment by edgardmessias** [comment]
Yes

**Comment by edgardmessias** [comment]
Done

**Comment by JohnstonCode** [comment]
Perfect

**Pull request merged**
