### PR TITLE
refactor: Removed check active editor from model (#443)

### PR DESCRIPTION
**Pull request by edgardmessias**
My idea to improve `model.ts`:

- Create more events (When necessary)
- Move code to another files and use events

### CODE REVIEW

**Comment by JohnstonCode** [comment]
How do we use contexts?

**Comment by edgardmessias** [comment]
Used to show/hide "Open changes BASE/HEAD" in editor

Here:
https://github.com/JohnstonCode/svn-scm/blob/69aa2bff85e8d9fd1bd6616abc03fd10beffc0c4/package.json#L424

https://github.com/JohnstonCode/svn-scm/blob/69aa2bff85e8d9fd1bd6616abc03fd10beffc0c4/package.json#L798

**Comment by JohnstonCode** [comment]
Aaah right. Was looking through VS docs and found nothnig that referenced them thats all

**Pull request merged**
