### PR TITLE
Publish code coverage results

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Don't we need a command to send it to codecov?

**Comment by edgardmessias** [comment]
I can add command too, I am reading the Azure Pipeline documentation

**Comment by JohnstonCode** [comment]
Think `- bash <(curl -s https://codecov.io/bash)` should work

**Comment by edgardmessias** [comment]
The current Codecov Report can be ignored

**Comment by JohnstonCode** [comment]
fixes #507

**Pull request merged**
