### PR TITLE
Fixed utf8 problem in diff (See #82, #9);

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Fixes #82 but not #9

**Comment by JohnstonCode** [comment]
Think the only way to get this working reliably is to get the encoding from the editor window the file is open in.

**Comment by edgardmessias** [comment]
@JohnstonCode, you can test again?

**Comment by JohnstonCode** [comment]
Yeah i will retest this later. Looks like it could work.

**Comment by JohnstonCode** [comment]
Works on the test file i was sent

**Pull request merged**
