### PR TITLE
Fixed compiler erros (Close #77)

### LINKED ISSUE #77: clean up all the errors in ts complier after npm update
Steps to Reproduce:

1. run npm update
2. see all the errors

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
There are more errors than that. Run npm update

**Comment by edgardmessias** [comment]
In travis is ok: https://travis-ci.org/JohnstonCode/svn-scm/builds/311990251

My Machine is OK

**Comment by JohnstonCode** [comment]
Ok ill merge and do the others. Think its a vs code type update doing it

**Comment by edgardmessias** [comment]
Send me examples of erros, please.

**Comment by JohnstonCode** [comment]
ignore me didn't run postinstall

**Pull request merged**
