### PR TITLE
chore: Improved workflow

### PR DESCRIPTION
**Pull request by edgardmessias**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Do we not want to be caching node_modules?

**Comment by edgardmessias** [comment]
Because there are no difference in my tests, probably there are a github proxy/cache for npm modules.

**Comment by JohnstonCode** [comment]
Yeah must be only took 13 seconds.

**Comment by edgardmessias** [comment]
Small note: I use `${{ github.run_id }}` in cache key for vscode, because each day, the insiders version change and the github cache is immutable.
Some times stable version change too.
Is most cheap to store cache every run

**Comment by JohnstonCode** [comment]
Yeah i saw that.

**Pull request merged**
