### PR TITLE
feat: Add remove unversioned command

### LINKED ISSUE #557: Add svn cleanup command
- VSCode Version: 1.33.1
- OS Version: kubuntu 19.04
- Extension Version: 1.48.1
- System Language:
- SVN Version: 1.10

## Steps to Reproduce ##

1. `ln -s aaa bbb`
2. Delete bbb

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

### PR DESCRIPTION
**Pull request by Yanpas**
The only thing that I would like to discuss with you is `logOutput`. I've made it public since I think we must inform user whatever actually happened.

I propose a global function, maybe in utils, which will log everything to outputChannel. Under the hood it will emit events, which output channel will be subscribed to.

### CODE REVIEW

**Comment by Yanpas** [comment]
And this feature is available only since 1.9

**Comment by Yanpas** [comment]
I think the better solution would be to set vscode-variable svn_gt_1_9 to true or false and depending on that show or hide commands, but since `Svn` is not singleton I decided to do it in this way

**Comment by Yanpas** [comment]
My local prettylint does not complain about src/test/testUtil.ts, it actually has fixed it. ver 1.0.0

**Comment by JohnstonCode** [comment]
A better way would be to create a svn version context and then do a check on that

**Comment by Yanpas** [comment]
done

**Comment by JohnstonCode** [comment]
Can you check that the changes i have made are working for you?

**Comment by Yanpas** [comment]
Yep, working fine

**Pull request merged**
