### PR TITLE
fix: testing files for being repository #661

### PR DESCRIPTION
**Pull request by Yanpas**

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Can you explain the change?

**Comment by Yanpas** [comment]
I've changed onPossibleSvnRepositoryChange to filter out files. This event was triggered with too many files so extension host process used 100% cpu nealry all the time.

I think it doesn't make any sence to call tryOpenRepository on file

**Comment by JohnstonCode** [comment]
I will have a look at the profile today and see if there is anything else that can be done.

**Comment by JohnstonCode** [comment]
I am still looking into this. Need a couple of days to think if there is a more efficient way to do this.

**Comment by JohnstonCode** [comment]
How many externals do you have?

**Comment by Yanpas** [comment]
None

**Comment by JohnstonCode** [comment]
Guessing you have lots of ignored things then?

**Comment by Yanpas** [comment]
global-ignores list is not so big, maybe there are a lot of subfolders with `svn:ignore` property.

`find trunk -type d | grep -v tmp/release | wc -l`: 18630.

The most significant performance impact had java extension recompiling code in the background and placing it in global ignored folder EclipseBuild

**Comment by JohnstonCode** [comment]
Can you use this https://github.com/JohnstonCode/svn-scm/suites/622540169/artifacts/4928564 and do a profile for me like the one you did before.

**Comment by Yanpas** [comment]
here it is: `WARN UNRESPONSIVE extension host, 'johnstoncode.svn-scm' took 90% of 3555.954ms, saved PROFILE here: '/tmp/exthost-75c372.cpuprofile`

[exthost-75c372.cpuprofile.txt](https://github.com/JohnstonCode/svn-scm/files/4523756/exthost-75c372.cpuprofile.txt)

**Comment by JohnstonCode** [comment]
Can you do another profile with https://github.com/JohnstonCode/svn-scm/suites/622662360/artifacts/4930963 and i will have a look at it tomorrow

**Comment by Yanpas** [comment]
Still getting profiles with java extension rebuilding sources
[exthost-80d6bb.cpuprofile.txt](https://github.com/JohnstonCode/svn-scm/files/4524333/exthost-80d6bb.cpuprofile.txt)

But overall it seems better

**Comment by JohnstonCode** [comment]
Can i have another profile with this build please https://github.com/JohnstonCode/svn-scm/suites/624652792/artifacts/4976440

**Comment by Yanpas** [comment]
[exthost-06cd83.cpuprofile.txt](https://github.com/JohnstonCode/svn-scm/files/4528626/exthost-06cd83.cpuprofile.txt)

**Comment by JohnstonCode** [comment]
Can you give this build a try. Doing some async stuff see if it makes a difference https://github.com/JohnstonCode/svn-scm/suites/625176878/artifacts/4989085

**Comment by Yanpas** [comment]
This warning is gone, see no profile warnings anymore. Tried to write it manually (from Show Running Extensions), but chrome perf anaylzer doesn't load it. I think the issue is resolved.

BTW why do you think that filtering out only directories is bad idea? (extra IO `stat` operation?)

**Comment by Yanpas** [comment]
Still extension host shows high cpu usage, and svn has maximum cpu time.

image

**Comment by Yanpas** [comment]
Actually extension gone mad, it creates svn process for every file that gets recompiled, from SVN log:
```
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
[trunk]$ svn: E200009: Could not display info for all targets because some targets don't exist[trunk]$ svn info --xml /home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class
[trunk]$ svn: warning: W155010: The node '/home/yanpas/ssd/work/trunk/EclipseBuild/%javapackage%/javaclass.class' was not found.
```
I hid actual classes names, but there are a lot of them.

Now it's UI can't get updated until all svn processes finish. I see no other way than reduce time complexity of this event by some filters

**Comment by JohnstonCode** [comment]
Yeah i was trying to off load everything on the main thread by spinning up CP and getting them to check with svn. The directory check will cause extra IO and shouldn't folder changes trigger this like changes to svn properties? Need to think of a better way to approach this.

**Comment by Yanpas** [comment]
> shouldn't folder changes trigger this like changes to svn properties

Properties stored in .svn/wc.db, `SELECT properties,local_relpath FROM NODES_CURRENT;`. When editing prperties temporary files are generated, but they still will be reported as directory event

**Comment by Yanpas** [comment]
Related issue
https://github.com/eclipse/eclipse.jdt.ls/issues/1425

**Comment by Blashaq** [comment]
I was also having trouble with this. Extension seems to fire off tons of `svn info` commands when modifying files in repository using external tools (e.g SVNTortoise updating working copy)

```
[trunk]$ svn info --xml c:\Repozytorium\trunk
```
I've had literally hundreds of those called simultaneously. This even managed to crash our SVN server a few times.

Looking forward to this PR.

**Pull request closed without merging**
