### PR TITLE
added option to ignore unversioned files

### PR DESCRIPTION
**Pull request by JohnstonCode**
Added the command to "scm/resourceState/context" to allow unversioned files to be ignored.

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Directories work fine. @edgardmessias what do you think about the recursive option?

**Comment by edgardmessias** [comment]
The tortoise SVN has 4 option
* Only the file file
* By File extension
* Only the file file (recursive)
* By File extension (recursive)

**Comment by JohnstonCode** [comment]
Yeah saw that on tortoise.

The issue with that is how do we decide what directory we are setting the svn ignore on if we allow wildcards to be set.

**Comment by edgardmessias** [comment]
Use like tortoise, use the directory of file.

For future, we create option to edit all properties.

**Comment by JohnstonCode** [comment]
That's what is currently does.

Any of the wildcard stuff can be done later if requested.

**Comment by edgardmessias** [comment]
Ok, only need fix the naming

**Comment by JohnstonCode** [comment]
suggestions on the name?

**Comment by edgardmessias** [comment]
See the review, `svn.AddFileToIgnore`, `async addFileToIgnore`

**Pull request merged**
