### PR TITLE
fix: Added --parents flag to update of remote files

### LINKED ISSUE #576: Cannot update files
Hi,

I noticed a certain behaviour in eclipse editor when using subclipse plugin and observed the same in your VSCode plugin.
I look at the files that are changed on remote. I right click a file and choose Update. The file is not loaded and an error is printed in the console: `Path is not a working copy directory`. This is because the directory structure for that file is not complete o the client. In my image the directory I highlighted yellow does not exist.
The solution is to call `svn update ..` with the `--parents` switch. This checks out the parent folders of the selected file.

grafik

### PR DESCRIPTION
**Pull request by JohnstonCode**
fix #576

### CODE REVIEW

**Comment by JohnstonCode** [comment]
`--parents` was added in 1.7. This will casue issues for people still using 1.6. I would run the update as normal and if it fails retry with the `--parents` flag. Doing it this way will mean that 1.6 shouldn't break. ideas?

**Comment by JohnstonCode** [comment]
Or could just do a version check and add the flag if version is on or above `1.7`

**Comment by JohnstonCode** [comment]
Why is that a problem? I thought the `--parents` flag only creates non existent directories

**Comment by edgardmessias** [comment]
We need to do more tests to avoid side effects

**Pull request closed without merging**
