### PR TITLE
Hist lens

### PR DESCRIPTION
**Pull request by Yanpas**
It's not fully featured as gitlens, but very handy already.
image

### CODE REVIEW

**Comment by Yanpas** [comment]
Despite I've tested it myself and think it's release-ready, I'm not sure it's polished enough. Currently I don't handle in diff directory paths e.g.

**Comment by JohnstonCode** [comment]
I'll take a look at it this weekend

**Comment by JohnstonCode** [comment]
Can you have a look at why the builds are failing?

**Comment by Yanpas** [comment]
Hm, maybe because I've upgraded target javascript to ES2017.
Also I've noticed `export CODE_VERSION=1.20.0`? but this branch reuires 1.28

**Comment by JohnstonCode** [comment]
we shouldn't be making any changes to the compiler options.

**Comment by edgardmessias** [comment]
@Yanpas, about the VSCode 1.28, you can make like it: https://github.com/JohnstonCode/svn-scm/blob/master/src/util.ts#L122

You can check the resource is avaiable or compare the VSCode version.

Some peoples use old version of VSCode.

**Comment by Yanpas** [comment]
I need version higher than 1.20 since old TreeView API misses some fields in the interface. Tests seem to work, but travis still fails to execute some

**Comment by edgardmessias** [comment]
First, @Yanpas, you are making a greate job.

**Comment by edgardmessias** [comment]
@Yanpas, @JohnstonCode 
First, @Yanpas , you are making a greate job, but I refuse to merge this pull request.

You need split some changes first, this pull request is very big.

**Comment by Yanpas** [comment]
You mean several pull requests? How the changes should be splitted? I only imagine two pull requests: first containts modifications of existing code base, second new .ts files and updated package.json

**Comment by edgardmessias** [comment]
You can end you branch, but some changes you can make before.

Example of split:
 * Commands for diff
 * Command for open remote file
 * Change of model.ts (You can explain the change?)
 * tempFiles (You can use the `tmp` lib)
 * Copy message log to clipboard (After this pull)

**Pull request closed without merging**
