### PR TITLE
Added support to changelists (Close #95,#99)

### LINKED ISSUE #95: Feature request multiple change lists
Support for multiple change lists would be nice.

Concrete I have the following "issue". Sometimes I change some config files like server-address or so for developing / debugging. For preventing me of accidentally committing these file, I have a change list "dont commit", where I put those changes in, which I like a lot...

### PR DESCRIPTION
**Pull request by edgardmessias**
* On commit, you can choose the "Changes" or one changelist
* Can add or remove files in changelist
* For renamed files, the old file is commited on commit

See #95 and #99

### CODE REVIEW

**Comment by JohnstonCode** [comment]
I’ll test this tomorrow and if all is good I’ll update it tomorrow

**Comment by edgardmessias** [comment]
Great

**Comment by JohnstonCode** [comment]
Is there a command to commit a change list?

**Comment by edgardmessias** [comment]
At commit time, if you have changelist, it asks which changelist

**Comment by JohnstonCode** [comment]
Yes, it does. I was trying it with no changes and a changelist.

It does commit the changelist if there is only one and no changes. Should this be the default behaviour?

**Comment by JohnstonCode** [comment]
For example, if you create a changelist called "do not commit" and run commit with no changes it will commit the list.

**Comment by edgardmessias** [comment]
Sorry for the delay to respond.

I can change to ask ever when I have a changelist

**Pull request merged**
