### PR TITLE
debounce svn info calls on filesystem events

### PR DESCRIPTION
**Pull request by Blashaq**
Reason for this change:

Filesystem events on workspace folders can cause a lot of `svn info` calls, which can heavily burden SVN servers. 
This can happen when an external tool updates working copy (SVNTortoise).
With this change, extension will only request info from remote, when filesystem has stabilized and no more FS events are firing.

### CODE REVIEW

**Comment by JohnstonCode** [comment]
Thanks for submitting this PR. All looks good. Can you please run `yarn lint:fix` to fix the style issues then i can merge this.

**Comment by Blashaq** [comment]
All done and ready.

**Comment by Blashaq** [comment]
Can i please ask you to merge this PR? It seems that everything is in order.

**Comment by JohnstonCode** [comment]
Feel free to submit the PR again and i can merge today.

**Pull request closed without merging**
