### PR TITLE
feat: Allow select files to commit when choose "changes" (close #472)

### LINKED ISSUE #472: Ctrl + Enter for commit doesn't give option to choose "Selected" files
When pressing Ctrl + Enter to commit, if you've specifically selected files, the pop-up dialog asks if you'd like to commit Changes or Changelist "Default", it does not either automatically choose selected files or even give the option.

The ideal solution IMO would be to add "Selected" to the pop-up dialog asking which files to commit.

### PR DESCRIPTION
**Pull request by edgardmessias**
image
image

I need update the tests

### CODE REVIEW

**Comment by JohnstonCode** [comment]
fixes #472

**Comment by JohnstonCode** [comment]
Should the default behaviour be to select all files?

**Comment by edgardmessias** [comment]
I think better to create a option, and user can change the default behavior (default: `None`)

**Comment by JohnstonCode** [comment]
Would this be better as a separate command `Select files to commit`?

**Comment by edgardmessias** [comment]
No, because you can select some files and use `Commit selected`

**Comment by JohnstonCode** [comment]
Okay, I also think the default open should be all. As that is the current behaviour

**Comment by JohnstonCode** [comment]
Add a config option and we are good

**Comment by edgardmessias** [comment]
Ok, I will make the changes

**Pull request merged**
