### PR TITLE
fix: Slow performance caused by too many isDescendant

### PR DESCRIPTION
**Pull request by JohnstonCode**
@edgardmessias what were the replaces for? Is it for when comparing external paths?

### CODE REVIEW

**Comment by JohnstonCode** [comment]
@Yanpas if you wana build this PR locally and see if you still having any issues that would be great.

**Comment by JohnstonCode** [comment]
fixes #661

**Comment by edgardmessias** [comment]
Not good for me, because sometimes, I see path like: `/c:/test/abc`

**Comment by JohnstonCode** [comment]
Can you give me a complete example so i have somethnig to test against?

**Comment by JohnstonCode** [comment]
Even with a path like `/c:/test/abc` the changes will still give the same results without the replaces

**Comment by Yanpas** [comment]
No, it doesn't help. Launched in debug and paused from debugger, it always stops at normalizeString, line 63. Will try to profile...

**Comment by JohnstonCode** [comment]
That is due to the join at https://github.com/JohnstonCode/svn-scm/blob/master/src/model.ts#L350 i belive

**Comment by JohnstonCode** [comment]
@Yanpas Can you do anyother profile while running this branch

**Comment by Yanpas** [comment]
Maybe it has something to do with new async IO. Maybe process-wide IO queue (libuv) gets overflowed with requests from extension and whole process goes slow. My project has a lot of nested folders, big files etc. 11 GB total.

My problem is related to editing files. Steps to reproduce that I use:
1. Start editing some file, save it
2. While it is saving diff is loaded, I can't edit it for 5 seconds
3. Repeat

Will try updated branch soon

**Comment by Yanpas** [comment]
[CPU-20191004T181347.244Z.cpuprofile.txt](https://github.com/JohnstonCode/svn-scm/files/3691769/CPU-20191004T181347.244Z.cpuprofile.txt)

**Comment by JohnstonCode** [comment]
Not sure how this can be fixed on a big project with the recursion. The git extension avoids this be only ever looking 1 level deep

**Comment by JohnstonCode** [comment]
@Yanpas if you set `svn.multipleFolders.depth` to 1 is the problem still present?

**Comment by Yanpas** [comment]
Seems like this setting has no impact on freezes

**Comment by Yanpas** [comment]
The stack trace above was due to lags on start of extension, I'll post traces while editing files

**Comment by JohnstonCode** [comment]
Can you console log all the joins and count how many it tries to do

**Comment by JohnstonCode** [comment]
Im getting like 4/5 on the project i have open

**Comment by JohnstonCode** [comment]
Can you give me a sample of what it is trying to join as well?

**Comment by Yanpas** [comment]
length is 1893. Yeah it's strage that while saving file I was editing extension is searching for repositories.
Stack traces
image

image

**Comment by JohnstonCode** [comment]
@Yanpas If you change `svn.detectIgnored` to false on the live extension do you have the issue?

**Comment by Yanpas** [comment]
Yes, it seems to help!

**Pull request closed without merging**
