### PR TITLE
changes with PREV

### LINKED ISSUE #377: Add command to compare WC-version with PREV
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Command which opens diff with -rPREV option

**Describe alternatives you've considered**
Also introduce a button? I guess 3 is too much

**Additional context**
Maybe -rBASE:PREV is more useful?

### PR DESCRIPTION
**Pull request by Yanpas**
Fixes #377

### CODE REVIEW

**Comment by edgardmessias** [comment]
@Yanpas, please, sync the branch and check the continuous integration

**Comment by Yanpas** [comment]
synced

**Comment by JohnstonCode** [comment]
@Yanpas can you squash all your commits and prefix the commit message with "feat: " please.

**Comment by JohnstonCode** [comment]
Thanks @Yanpas

**Pull request merged**
