### PR TITLE
use at revision, fixes

### LINKED ISSUE #489: Svn repo history diff of deleted files doesn't work
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:
- SVN Version:

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

### PR DESCRIPTION
**Pull request by Yanpas**
see https://stackoverflow.com/questions/16846155

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Fixes #489

# Description

See https://stackoverflow.com/questions/16846155/svn-cat-on-older-revision-location

This commit mainly adds `@revision` to each log/cat commands

## Type of change

[ x] Bug fix (non-breaking change which fixes an issue)  
[ ] New feature (non-breaking change which adds functionality)  
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
[ ] This change requires a documentation update  

# How Has This Been Tested?
On my work's svn repo

# Checklist:
[x ] My code follows the style guidelines of this project  
[ x] I have performed a self-review of my own code  
[ ] I have commented my code, particularly in hard-to-understand areas  
[ ] I have made corresponding changes to the documentation  
[ x] My changes generate no new warnings  
[ ] I have added tests that prove my fix is effective or that my feature works  
[ x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Yanpas** [comment]
Ain't ready yet, using pr for ci purposes

**Comment by Yanpas** [comment]
Ready

**Comment by Yanpas** [comment]
Something weird happens to macos

**Comment by JohnstonCode** [comment]
Yeah not sure what’s causing that. I’ll have a proper look tomorrow

**Comment by JohnstonCode** [comment]
`svn: E125002: URL 'file:///var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/svn_server_4051CK5bSvqlDp7V/../../../../../../var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/svn_checkout_405165ys5lp2PFj4/new.txt' contains a '..' element`

**Comment by JohnstonCode** [comment]
@Yanpas can you open a new PR CI seems to be broken after the switch

**Pull request closed without merging**
