### PR TITLE
Fix svn not found

### LINKED ISSUE #386: Warning SVN not found. Install it or configure it using the 'svn.path' setting.
- VSCode Version: 1.28
- OS Version: kubuntu 18.04
- Extension Version: 1.44
- System Language:
- SVN Version: 1.9.7

## Issue ##
Sometimes after reloading vscode window (after extensions update) I see following warning:
> SVN not found. Install it or configure it using the 'svn.path' setting.

The folder which I'm opening doesn't contain svn repository, only git.

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

### PR DESCRIPTION
**Pull request by Yanpas**
fixes #386

### CODE REVIEW

**Comment by edgardmessias** [comment]
Thanks @Yanpas 

Join on https://gitter.im/svn-scm/Lobby

**Comment by Yanpas** [comment]
Thanks for invite!

**Comment by JohnstonCode** [comment]
Fixes the issue for me

**Pull request merged**
