### PR TITLE
chore: bumped vscode engine version

### LINKED ISSUE #688: Keeping up with the latest vscode version
Should we keep up with the latest vscode version? Again just thinking about easer maintinance rather than having to think about our version, current version and insiders.

### PR DESCRIPTION
**Pull request by JohnstonCode**
fixes #688

### CODE REVIEW

**Comment by JohnstonCode** [comment]
@edgardmessias any ideas how to get the coverage working?

**Comment by edgardmessias** [comment]
> @edgardmessias any ideas how to get the coverage working?

I no know, we need check the `preset: "ts-jest"`, removing it generate the files, but wrong result

**Comment by JohnstonCode** [comment]
Cannot get the coverage working, reverted all my attempts
Alt Text

**Comment by edgardmessias** [comment]
We can't use the github workflow badge, because:
```
ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://github.com/JohnstonCode/svn-scm/workflows/build/badge.svg
```
Wait for https://github.com/microsoft/vscode-vsce/issues/389

**Comment by JohnstonCode** [comment]
Yeah saw that lastnight. Will disable for the time being

**Pull request merged**
