### PR TITLE
ci: dont think the plugins section is needed

### PR DESCRIPTION
**Pull request by JohnstonCode**
This might work?

### CODE REVIEW

**Comment by edgardmessias** [comment]
Example: 

```json
{
  "verifyConditions": [
    "@semantic-release/github",
    "@semantic-release/git",
    "@semantic-release/changelog",
    "semantic-release-vsce"
  ],
  "prepare": [
    "@semantic-release/npm",
    "@semantic-release/changelog",
    {
      "path": "@semantic-release/git",
      "assets": ["CHANGELOG.md", "package.json", "package-lock.json"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    },
    "semantic-release-vsce"
  ],
  "publish": [
    "semantic-release-vsce",
    {
      "path": "@semantic-release/github",
      "assets": "svn-scm.vsix"
    }
  ],
  "packageVsix": "svn-scm.vsix"
}

```

**Comment by JohnstonCode** [comment]
but packageVsix is needed in the prepare step, this is as it was before

**Comment by edgardmessias** [comment]
Yes, but the config `packageVsix` need in global config

**Comment by JohnstonCode** [comment]
But it wasn't a global config before and generated the vsix

**Comment by edgardmessias** [comment]
My local test (commented all dangerous action, like git push, fetch, ...), working fine with my comment: https://github.com/JohnstonCode/svn-scm/pull/382#issuecomment-430266376

**Comment by JohnstonCode** [comment]
Made the changes

**Pull request merged**
