### PR TITLE
ci: fix release json

### PR DESCRIPTION
**Pull request by JohnstonCode**

### CODE REVIEW

**Comment by edgardmessias** [comment]
In "package.json`: `"private": true`

**Comment by JohnstonCode** [comment]
Does the order change achieve the same result?

**Comment by edgardmessias** [comment]
Update:

Append after `"plugins"`, need for load the plugins, default only load npm github, commit-analyzer and release-notes-generator:

```json
  "prepare": [
    "@semantic-release/npm",
    "@semantic-release/changelog",
    "semantic-release-vsce",
    "@semantic-release/git"
  ]
```

Need

**Comment by JohnstonCode** [comment]
Changes made

**Pull request merged**
